### PR TITLE
add simple search

### LINKED ISSUE #23: Search is broken on plugins.drone.io
Nothing happens when you type anything in. Seems to work on the other subdomains.

### PR DESCRIPTION
**Pull request by lizheming**
To fix drone/drone-plugin-index#23 I create this pr. It seems plugin index site can search by algolia's docsearch. But it have not set algolia_key config now. So I add an simple search feature for plugin index by css and little js code. Because `/dist/script.min.js` is an uglify file, so I add search code with script tag.

### CODE REVIEW

**Comment by tboerger** [comment]
Maybe @bradrydzewski needs to clarify how the search should work. Have this been handled via Caddy search plugin?

**Comment by bradrydzewski** [comment]
We are using Algolia doc search which is free for open source
https://community.algolia.com/docsearch/

This would index the plugin names as well as their documentation. I haven't had time to get it enabled, but that is the approach I'd like to take.

**Comment by lizheming** [comment]
Yes, I found it, but as you said you have no time to do it. So I add this `else` case to approach search with low cost(https://github.com/drone/drone-hugo-theme/pull/2/files#diff-929a8a6e57dacfcbc3ef2392954dc249R26). It's just a back up method, if you get done docsearch and config it, this pr will not be used after generate. All in all, drone/drone-plugin-index#23 was created one year ago, I just want to do something to fix it. If you think this is not required, you can close this and drone/drone-plugin-index#103 pr. I'm very glad to see that. Thank you~

**Comment by tboerger** [comment]
@bradrydzewski if the docs are served via caddy you could also use the caddy search plugin

**Comment by lizheming** [comment]
OK, It seems we needn't this simple search feature. So I close this pr for waiting algolia ready~ Thank you for your working~

**Pull request closed without merging**
